"""
2 - Problem 1
"""

import code_ece6280hw01_pb1 as pb1

cipher = "yysjxbysjxnkwkpjucfhyeswwyysotqcvwbxrzdinessgizoetugzwhwtvskidmsiucslkjvgobqcbwojiuwmftfglxrbvxfkhzxhfbwlzerwkmzghbsvgamjczzbrysggqpgsrxxcgwkvbuxxdocxlfcvgjzuzutigkiwzbybxkvwfnjqzbjwwffjrbvbbfbvxwztavtlzvizkofhyzcfbsywkajrroaduclajpasdjxcgwsvwyagffkbxehambysjxyysjxfisuhbjpmmmvfwmmvfwtwvbgvtngtxkffwbglwdmfnodenuokdyfyfhbnvsmnnokpfczaglzbgkbrzdbsxcmmferlhbycebbrgdbpvhgznmsgykvbkxxfawmmzbymmvfwbxkvsmifskgyccnxfnodeyyolpfehkbyucogntcmeijoqxqmskmtyweuzkwllsfhweavgwqfthdrferawwrhzxwysktnuwlytivafxvzxbxvszbrkvwkjsfaglzbytxkcfxliokijutakrcmtryyslhuzbwthyvsgicwcxfecdwxkcfxxrjszjrfexiysehavgagirfcgjjgslnkgwxrjhgfjeclhkncgwxfbdrferlajjvswjftlkjvgzxbzzdgtkugujywfwmzgxtyysjlxrmaglrbvajcwcxxyonbsxhzhzxvlhkzhkhbvzdajjoqlfxoaglfcvyjeqwlrrywztfrfxnxvthwj"

key = pb1.cryptanalysis_vigenere(cipher)
print(key)
print(pb1.decipher_vigenere(cipher, key))
